chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'
urlpatterns = [
 path('room/<int:course_id>/', views.course_chat_room,
 name='course_chat_room'),
]

education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from courses.views import CourseListView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/login',auth_views.LoginView.as_view(),name='login'),
    path('accounts/logout',auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('',CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('chat/',include("chat.urls",namespace='chat')),
    path('social-auth/',include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from django.conf.urls import url
import students.views as views
from django.views.decorators.cache import cache_page
urlpatterns = [
    # path('register/', views.StudentRegistrationView.as_view(), name='student_registration'), 
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/',views.StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<pk>/',cache_page(60*15)(views.StudentCourseDetailView.as_view()), name='student_course_detail'),
    path('course/<pk>/<module_id>/', cache_page(60*15)(views.StudentCourseDetailView.as_view()), name='student_course_detail_module'),
    url(r'^signup/$', views.signup, name='student_registration'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms
from courses.models import Course
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all(),
                                    widget=forms.HiddenInput)

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

students/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CourseEnrollForm, SignupForm

from django.views.generic.list import ListView
from courses.models import Course
from django.views.generic.detail import DetailView

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your user account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        return redirect('course_list')
    else:
        return HttpResponse('Activation link is invalid!')
# class StudentRegistrationView(CreateView):
#     template_name='students/student/registration.html'
#     form_class=UserCreationForm
#     success_url=reverse_lazy('student_course_list')

#     def form_valid(self, form):
#         result=super().form_valid(form)
#         cd=form.cleaned_data
#         user=authenticate(username=cd['username'], password=cd['password1'])
#         login(self.request, user)
#         return result

class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('student_course_detail',
                            args=[self.course.id])

class StudentCourseListView(LoginRequiredMixin, ListView):
    model=Course
    template_name='students/course/list.html'
    
    def get_queryset(self):
        qs= super().get_queryset()
        return qs.filter(students__in=[self.request.user])

class StudentCourseDetailView(DetailView):
    model=Course
    template_name='students/course/detail.html'
    
    def get_queryset(self):
         qs = super().get_queryset()
         return qs.filter(students__in=[self.request.user])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()
        if 'module_id' in self.kwargs:
            context['module']=course.modules.get(id=self.kwargs['module_id'])

        else:
            context['module']=course.modules.all()[0]
        return context

students/templates/students/course/detail.html
{% extends "base.html" %}
{% load cache %}
{% block title %}
    {{ object.title }}
{% endblock %}

{% block nav1 %}
    <li class="nav-item dropdown "> <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Modules</a>
     <div class="dropdown-menu" >
     
     {% for m in object.modules.all %}
     <a class='dropdown-item' href="{% url "student_course_detail_module" object.id m.id %}">
    <span>Module <span class="order">{{ m.order|add:1 }}</span></span>
    <br>
 {{ m.title }}
 </a>
    <div class="dropdown-divider"></div>
 {% empty %}
 <li>No modules yet.</li>
 {% endfor %}
     </div>
    </li>
    <li class='nav-item'><a class='nav-link' href="{% url "chat:course_chat_room" object.id %}">Course Chat</a></li>
{% endblock%}

{% block content %}

<div class='container-fluid'>
 <div class="sidebar" >
{% for m in object.modules.all %}<li>
<a data-id="{{ m.id }}" {% if m == module %}class=""{% else %}class=""{% endif %} href="{% url "student_course_detail_module" object.id m.id %}" >
    <span>Module <span class="order">{{ m.order|add:1 }}</span></span>
 {{ m.title }}
 </a></li>
 {% empty %}
 <li>No modules yet.</li>
 {% endfor %}
</div>

<div class="content"style="margin-top:5px;">
<div class='container-fluid'><h4 class="text-secondary" style="margin-top:10px;">{{object.subject}} Course :  {{object.title}}</h4></div>
<div class="card mb-3">
 {% cache 600 module_contents module%}
 <div class='card-body'>
 <div class ="row">
 {% for content in module.contents.all %}
 {% with item=content.item %}
 {% comment %} <h4 class='card-title'>{{ item.title|truncatechars:25 }}</h4> {% endcomment %}
 {{ item.render }}
 {% endwith %}
  {% empty %}
 <li>No content yet.</li>
 {% endfor %}
 </div>
 </div>
 {% endcache %}
      </div>
    </div>
</div>

{% endblock %}

{% block domready %}
 $('.dropdown-trigger').dropdown();
{% endblock%}
 
    {{item.content|linebreaks}}
       

students/templates/students/course/list.html
{% extends "base.html" %}
    {% block title %}My courses{% endblock %}
{% block content %}
 
  <div class="container-fluid">
   <h5 class="mt-2">My courses</h5>
<div class='row'>
 {% for course in object_list %}
    <div class='col-lg-6'>
    <div class="card">
    <div class="card-body">
        <h4 class="card-title">{{ course.title }}</h4>
         <p class="card-text">Owner : {{course.owner}}</p>
         <a class="card-link" href="{% url "student_course_detail" course.id %}">Access contents</a>
    </div>
    </div>
    </div>
 {% empty %}
    <p>
    You are not enrolled in any courses yet.
    <a href="{% url "course_list" %}">Browse courses</a>to enroll in a course.
    </p>
 {% endfor %}
 </div></div>
{% endblock %}